#!/bin/bash

rsync -avh --backup-dir=$(date +%F) \
  --exclude='sasaki/.cache/' \
  --exclude='sasaki/.dbus/' \
  --exclude='sasaki/.pki/' \
  --exclude='sasaki/.android/' \
  --exclude='sasaki/.gradle/' \
  --exclude='sasaki/.gnome/' \
  --exclude='sasaki/.java/' \
  --exclude='sasaki/.yarn/' \
  --exclude='sasaki/.react-native-cli/' \
  --exclude='sasaki/.local/lib' \
  --exclude='sasaki/Android/' \
  --exclude='sasaki/.local/share/Trash' \
  --exclude='sasaki/.config/chromium' \
  /home/sasaki homeserver:/mnt/remotes/western/Backup/
