#!/bin/sh
# Give dmenu list of all unicode characters to copy.
# Shows the selected character in dunst if running.

# Must have xclip installed to even show menu.
xclip -h >/dev/null || exit

dmenu="/usr/local/bin/dmenu"

chosen=$(grep -v "#" ~/.local/share/emoji/list | $dmenu -i -l 10 -fn Monospace-18)

[ "$chosen" != "" ] || exit

c=$(echo "$chosen" | sed "s/ .*//")
echo "$c" | tr -d '\n' | xclip -selection clipboard
notify-send "$c copied to clipboard." &
