#!/bin/sh

sink=$(pactl list sinks short | grep bluez | awk '{print $1}') || 0
[ -z "$sink" ] && sink=0

raise_volume() {
  pactl set-sink-volume $sink +5%
}

lower_volume() {
  pactl set-sink-volume $sink -5%
}

toggle_mute() {
  pactl set-sink-mute $sink toggle
}

[ "$1" == "raise" ] && raise_volume && exit
[ "$1" == "lower" ] && lower_volume && exit
[ "$1" == "mute" ] && toggle_mute && exit
