#!/bin/bash

[[ "$1" == "--audio" ]] && yt-dlp -f 'bestaudio[ext=m4a]' -o "~/Downloads/%(title)s.%(ext)s" $2 && exit
[[ "$1" == "--file" ]] && yt-dlp -f best -a $2 -o "~/Downloads/%(title)s.%(ext)s" && exit

[[ "$1" == "--file" ]] && [[ "$1" == "--audio" ]] && yt-dlp -f 'bestaudio[ext=m4a]' -a $2 -o "~/Downloads/%(title)s.%(ext)s" $2 && exit

yt-dlp -o "~/Downloads/%(title)s.%(ext)s" "$1"
