vim.opt.clipboard = "unnamedplus"               -- allows neovim to access the system clipboard
vim.opt.relativenumber = true                   -- set relative numbered lines
vim.opt.wrap = false                            -- display lines as one long line
vim.opt.numberwidth = 2                         -- set number column width to 2 {default 4}
vim.opt.number = true                           -- set numbered lines
vim.opt.cursorline = true                       -- highlight the current line
vim.opt.tabstop = 2                             -- insert 2 spaces for a tab
vim.opt.shiftwidth = 2                          -- the number of spaces inserted for each indentation
vim.opt.expandtab = true                        -- convert tabs to spaces
