#!/bin/sh

case $BUTTON in
	1) mpc toggle | filter ;;  # right click, pause/unpause
	2) mpc status | filter ; setsid -f "$TERMINAL" -e ncmpcpp ;;  # right click, pause/unpause
	3) mpc status | filter ; "$TERMINAL" -e "$EDITOR" "$0" ;;
	4) mpc next   | filter ;;  # scroll up, previous
	5) mpc prev   | filter ;;  # scroll down, next
esac

current=$(mpc current)

if [ "$current" ]; then

	artist=$(mpc -f '%artist%' | head -1)
	title=$(mpc -f '%title%' | head -1)

	if [ ! "$title" ] && [ ! "$artist" ];then
		occurs=$(mpc -f %'file'% | head -1 | grep -o '/' | wc -l)
		occurs=$((occurs+1))
		title=$(mpc -f %'file'% | head -1 | cut -d '/' -f $occurs)
	elif [ ! "$title" ]; then
		occurs=$(mpc -f %'file'% | head -1 | grep -o '/' | wc -l)
		occurs=$((occurs+1))
		title=$(mpc -f %'file'% | head -1 | cut -d '/' -f $occurs)
	fi

  #echo "  $artist - $title "
  echo "  $title "
fi
