#!/bin/sh

case $BUTTON in
        1) notify-send "🖥 CPU hogs:" "$(ps axch -o cmd:15,%cpu --sort=-%cpu | head)" ;;
	2) setsid -f "$TERMINAL" -e htop ;;
	3) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

echo "  $(sensors | awk '/^temp1/ {print $2}' | cut -d '+' -f 2 | head -1) "
