#!/bin/sh

case $BUTTON in
	2) setsid -f "$TERMINAL" -e alsamixer ;;
	3) "$TERMINAL" -e "$EDITOR" "$0" ;;
	4) volume raise | pkill -RTMIN+11 dwmblocks;;
	5) volume lower | pkill -RTMIN+11 dwmblocks;;
esac

volume_status=$(pamixer --get-mute)

if [ $volume_status = "false" ]; then
   echo "  : $(pamixer --get-volume)"
else
   echo "  "
fi
