#!/bin/sh

case $BUTTON in
	1) notify-send "🧠 Memory hogs:" "$(ps axch -o cmd:15,%mem --sort=-%mem | head)" ;;
	2) setsid -f "$TERMINAL" -e htop ;;
        3) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

echo " : $(free -h | awk '/^Mem:/ {print $3}') "
